# Generated by Django 5.1.4 on 2024-12-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
